apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-deploy
spec:
  selector:
    matchLabels:
      app: ruby
  template:
    metadata:
      labels:
        app: ruby
    spec:
      containers:
      - name: ruby-img
        image: ogechi/vivicodes:ruby1
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            cpu: "50m"
            memory: "128Mi"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 30
        readinesProbe:
          httpGet:
            path: /healthcheck
            port: 80
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 30

          
