apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ruby
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ruby
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
  