apiVersion: v1
kind: Service
metadata:
  labels:
    app: ruby
  name: ruby-deploy
spec:
  selector:
    app: ruby
  ports:
  - nodePort: 30904
    port: 80
    targetPort: 80
    protocol: TCP
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: localhost